export const basename = "/Comanda-smeshariki/dist/"

export const GOODS = [
  {
    id: 0,
    title: "Крупная бытовая техника",
    category: "Холодильник",
    name: "Двухкамерный холодильник Haier",
    img: `${basename}/img/HugeTechnic/Холодильник.webp`,
    price: 54632,
    favours: false,
    storage: 23,
  },
  {
    id: 1,
    title: "Техника для дома",
    category: "Пылесос",
    name: "Пылесос вертикальный Habastore",
    img: `${basename}/img/HouseTechnic/Пылесос.webp`,
    price: 4257,
    favours: false,
    storage: 312,
  },
  {
    id: 2,
    title: "Техника для кухни",
    category: "Мультиварка",
    name: "Мультиварка Polaris",
    img: `${basename}/img/KitchenTechnic/Мультиварка.webp`,
    price: 8729,
    favours: false,
    storage: 2312,
  },
  {
    id: 3,
    title: "Крупная бытовая техника",
    category: "Стиральная машинка",
    name: "Стиральная машинка Bosch Serie",
    img: `${basename}/img/HugeTechnic/Стиральная машина.webp`,
    price: 17656,
    favours: false,
    storage: 1,
  },
  {
    id: 4,
    title: "Техника для дома",
    category: "Парогенератор",
    name: "Парогенератор Tefal",
    img: `${basename}/img/HouseTechnic/Парогенератор.webp`,
    price: 6894,
    favours: false,
    storage: 254,
  },
  {
    id: 5,
    title: "Техника для кухни",
    category: "Микроволновая печь",
    name: "Микроволновая печь Hyundai",
    img: `${basename}/img/KitchenTechnic/Микроволновая Печь.webp`,
    price: 20890,
    favours: false,
    storage: 22,
  },
  {
    id: 6,
    title: "Крупная бытовая техника",
    category: "Плита",
    name: "Электрическая плита Weissgauff",
    img: `${basename}/img/HugeTechnic/Плита.webp`,
    price: 19100,
    favours: false,
    storage: 278,
  },
  {
    id: 7,
    title: "Техника для дома",
    category: "Робот‑пылесос",
    name: "Робот-пылесос Roborock Qrevo L",
    img: `${basename}/img/HouseTechnic/Робот пылесос.webp`,
    price: 39990,
    favours: false,
    storage: 0,
  },
  {
    id: 8,
    title: "Техника для кухни",
    category: "Кофемашина",
    name: "Кофемашина автоматическая зерновая",
    img: `${basename}/img/KitchenTechnic/Кофемашина.webp`,
    price: 23057,
    favours: false,
    storage: 964,
  },
  {
    id: 9,
    title: "Крупная бытовая техника",
    category: "Сушильная машина",
    name: "Сушильная машина Hyundai",
    img: `${basename}/img/HugeTechnic/Сушильная машина.webp`,
    price: 40028,
    favours: false,
    storage: 657,
  },
  {
    id: 10,
    title: "Техника для дома",
    category: "Увлажнитель воздуха",
    name: "Увлажнитель воздуха",
    img: `${basename}/img/HouseTechnic/Увлажнитель воздуха.webp`,
    price: 4000,
    favours: false,
    storage: 1222,
  },
  {
    id: 11,
    title: "Техника для кухни",
    category: "Соковыжималка",
    name: "Соковыжималка электрическая Futula",
    img: `${basename}/img/KitchenTechnic/Соковыжималка.webp`,
    price: 3183,
    favours: false,
    storage: 332,
  },
  {
    id: 12,
    title: "Крупная бытовая техника",
    category: "Посудомоечная машина",
    name: "Посудомоечная машина Tuvio",
    img: `${basename}/img/HugeTechnic/Посудомоечная машина.webp`,
    price: 34521,
    favours: false,
    storage: 322,
  },
  {
    id: 13,
    title: "Техника для дома",
    category: "Отпариватель",
    name: "Отпариватель для одежды",
    img: `${basename}/img/HouseTechnic/Отпариватель.webp`,
    price: 3175,
    favours: false,
    storage: 312,
  },
  {
    id: 14,
    title: "Техника для кухни",
    category: "Блендер",
    name: "Блендер погружной",
    img: `${basename}/img/KitchenTechnic/Блендер.webp`,
    price: 6202,
    favours: false,
    storage: 549,
  },
  {
    id: 15,
    title: "Крупная бытовая техника",
    category: "Кондиционер",
    name: "Кондиционер NT-65CHW12",
    img: `${basename}/img/HugeTechnic/Кондиционер.webp`,
    price: 35000,
    favours: false,
    storage: 1509,
  },
  {
    id: 16,
    title: "Техника для дома",
    category: "Очиститель воздуха",
    name: "Очиститель воздуха SMARTMI",
    img: `${basename}/img/HouseTechnic/Очиститель воздуха.webp`,
    price: 19864,
    favours: false,
    storage: 764,
  },
  {
    id: 17,
    title: "Техника для кухни",
    category: "Электрочайник",
    name: "Электрочайник Centek",
    img: `${basename}/img/KitchenTechnic/Элкетрочайник.webp`,
    price: 1213,
    favours: false,
    storage: 543,
  },
  {
    id: 18,
    title: "Крупная бытовая техника",
    category: "Водонагреватель",
    name: "Водонагреватель накопительный Ресанта",
    img: `${basename}/img/HugeTechnic/Водонагреватель.webp`,
    price: 16728,
    favours: false,
    storage: 412,
  },
  {
    id: 19,
    title: "Техника для дома",
    category: "Мойка высокого давления",
    name: "Мойка высокого давления Huter",
    img: `${basename}/img/HouseTechnic/Мойка высокого давления.webp`,
    price: 12596,
    favours: false,
    storage: 675,
  },
  {
    id: 20,
    title: "Техника для кухни",
    category: "Тостер",
    name: "Тостер Xiaomi",
    img: `${basename}/img/KitchenTechnic/Тостер.webp`,
    price: 3034,
    favours: false,
    storage: 4125,
  },
  {
    id: 21,
    title: "Крупная бытовая техника",
    category: "Морозильная камера",
    name: "Морозильная камера HYUNDAI",
    img: `${basename}/img/HugeTechnic/Морозильная камера.webp`,
    price: 29606,
    favours: false,
    storage: 464,
  },
  {
    id: 22,
    title: "Техника для дома",
    category: "Осушитель воздуха",
    name: "Осушитель воздуха",
    img: `${basename}/img/HouseTechnic/Осушитель воздуха.webp`,
    price: 14596,
    favours: false,
    storage: 6612,
  },
  {
    id: 23,
    title: "Техника для кухни",
    category: "Мясорубка",
    name: "Мясорубка электрическая",
    img: `${basename}/img/KitchenTechnic/Мясорубка электрическая.webp`,
    price: 5945,
    favours: false,
    storage: 755,
  },
  {
    id: 24,
    title: "Крупная бытовая техника",
    category: "Духовой шкаф",
    name: "Духовой шкаф LEX EDP",
    img: `${basename}/img/HugeTechnic/Духовой шкаф.webp`,
    price: 21000,
    favours: false,
    storage: 644,
  },
  {
    id: 25,
    title: "Техника для дома",
    category: "Паровая швабра",
    name: "Паровая швабра Smartex",
    img: `${basename}/img/HouseTechnic/Паровая швабра.webp`,
    price: 5710,
    favours: false,
    storage: 654,
  },
  {
    id: 26,
    title: "Техника для кухни",
    category: "Хлебопечка",
    name: "Хлебопечка GURMAN",
    img: `${basename}/img/KitchenTechnic/Хлебопечка.webp`,
    price: 7711,
    favours: false,
    storage: 251,
  },
  {
    id: 27,
    title: "Крупная бытовая техника",
    category: "Газовая плита",
    name: "Газовая плита Weissgauff",
    img: `${basename}/img/HugeTechnic/Газовая плита.webp`,
    price: 17290,
    favours: false,
    storage: 777,
  },
  {
    id: 28,
    title: "Техника для дома",
    category: "Робот‑мойщик окон",
    name: "Робот мойщик окон Domashi Ley",
    img: `${basename}/img/HouseTechnic/Робот мойщик окон.webp`,
    price: 35699,
    favours: false,
    storage: 53,
  },
  {
    id: 29,
    title: "Техника для кухни",
    category: "Фритюрница",
    name: "Фритюрница Kitfort",
    img: `${basename}/img/KitchenTechnic/Фритюрница.webp`,
    price: 6500,
    favours: false,
    storage: 124,
  },
  {
    id: 30,
    title: "Крупная бытовая техника",
    category: "Котел отопления",
    name: "Котел наружного размещения",
    img: `${basename}/img/HugeTechnic/Котёл отопления.webp`,
    price: 149100,
    favours: false,
    storage: 425,
  },
  {
    id: 31,
    title: "Техника для дома",
    category: "Вентилятор",
    name: "Вентилятор настольный MARTA",
    img: `${basename}/img/HouseTechnic/Вентилятор.webp`,
    price: 886,
    favours: false,
    storage: 214,
  },
  {
    id: 32,
    title: "Техника для кухни",
    category: "Электрогриль",
    name: "Электрогриль Polaris",
    img: `${basename}/img/KitchenTechnic/Электрогриль.webp`,
    price: 5099,
    favours: false,
    storage: 2364,
  },
  {
    id: 33,
    title: "Крупная бытовая техника",
    category: "Посудомоечная машина встраиваемая",
    name: "Посудомоечная машина Weissgauff встраиваемая",
    img: `${basename}/img/HugeTechnic/Посудомоечная машина встраимавая.webp`,
    price: 32000,
    favours: false,
    storage: 666,
  },
  {
    id: 34,
    title: "Техника для дома",
    category: "Массажный матрас",
    name: "Массажный матрас электрический",
    img: `${basename}/img/HouseTechnic/Массажный матрас.webp`,
    price: 6788,
    favours: false,
    storage: 31,
  },
  {
    id: 35,
    title: "Техника для кухни",
    category: "Йогуртница",
    name: "Йогуртница  Centek",
    img: `${basename}/img/KitchenTechnic/Йогуртница.webp`,
    price: 2631,
    favours: false,
    storage: 43,
  },
  {
    id: 36,
    title: "Крупная бытовая техника",
    category: "Сплит‑система",
    name: "Сплит‑система Бирюса",
    img: `${basename}/img/HugeTechnic/Сплит-система.webp`,
    price: 15462,
    favours: false,
    storage:64,
  },
  {
    id: 37,
    title: "Техника для дома",
    category: "Аквариумная помпа",
    name: "Помпа для аквариума QL-618",
    img: `${basename}/img/HouseTechnic/Аквариумная помпа.webp`,
    price: 1028,
    favours: false,
    storage: 64,
  },
  {
    id: 38,
    title: "Техника для кухни",
    category: "Мини‑печь",
    name: "Мини‑печь GURMAN",
    img: `${basename}/img/KitchenTechnic/Мини-печь.webp`,
    price: 5661,
    favours: false,
    storage: 123,
  },
  {
    id: 39,
    title: "Крупная бытовая техника",
    category: "Варочная панель",
    name: "Варочная панель электрическая",
    img: `${basename}/img/HugeTechnic/Варочная панель.webp`,
    price: 7031,
    favours: false,
    storage: 0,
  },
  {
    id: 40,
    title: "Техника для дома",
    category: "Электрокотел",
    name: "Электрокотел Intois",
    img: `${basename}/img/HouseTechnic/Электрокотёл.webp`,
    price: 102352,
    favours: false,
    storage: 76,
  },
  {
    id: 41,
    title: "Техника для дома",
    category: "Швейная машина",
    name: "Швейная машина Stoewer",
    img: `${basename}/img/HouseTechnic/Швейная машина.webp`,
    price: 16354,
    favours: false,
    storage: 242,
  },
  {
    id: 42,
    title: "Крупная бытовая техника",
    category: "Тепловая пушка",
    name: "Тепловая пушка электрическая",
    img: `${basename}/img/HugeTechnic/Тепловая пушка.webp`,
    price: 3224,
    favours: false,
    storage: 543,
  },
  {
    id: 43,
    title: "Техника для дома",
    category: "Озонатор",
    name: "Озонатор для дома",
    img: `${basename}/img/HouseTechnic/Очиститель воздуха.webp`,
    price: 7000,
    favours: false,
    storage: 11,
  },
  {
    id: 44,
    title: "Техника для кухни",
    category: "Сэндвичница",
    name: "Сэндвичница RAGEX",
    img: `${basename}/img/KitchenTechnic/Сэндвиничница.webp`,
    price: 2690,
    favours: false,
    storage: 523,
  },
  {
    id: 45,
    title: "Техника для кухни",
    category: "Сушилка для овощей и фруктов",
    name: "Сушилка для овощей и фруктов",
    img: `${basename}/img/KitchenTechnic/Сушилка для овощей и фруктов.webp`,
    price: 12573,
    favours: false,
    storage: 8757,
  },
  {
    id: 46,
    title: "Техника для дома",
    category: "Электрокамин",
    name: "Электрокамин ELEKAM",
    img: `${basename}/img/HouseTechnic/Электрокамин.webp`,
    price: 39655,
    favours: false,
    storage: 543,
  },
  {
    id: 47,
    title: "Крупная бытовая техника",
    category: "Кулер",
    name: "Кулер для воды Starwind",
    img: `${basename}/img/HugeTechnic/Кулер.webp`,
    price: 3717,
    favours: false,
    storage: 765,
  },
  {
    id: 48,
    title: "Крупная бытовая техника",
    category: "Морозильный ларь",
    name: "Морозильный ларь Бирюса",
    img: `${basename}/img/HugeTechnic/Морозильный ларь.webp`,
    price: 16790,
    favours: false,
    storage: 643,
  },
  {
    id: 49,
    title: "Техника для дома",
    category: "Утюг",
    name: "Утюг Haier",
    img: `${basename}/img/HouseTechnic/Утюг.webp`,
    price: 5276,
    favours: false,
    storage: 765,
  }
];
